name: Dockerize the Application
on:
  push:
    branches:
      - master

jobs:
  buildapp-authedgateway:
    name: Build JobsApi.AuthedGateway Docker Image & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & Push JobsApi.AuthedGateway Docker Image
        with:
          image: ghcr.io/mrkresnofatih/jobsapi-authedgateway
          registry: ghcr.io
          dockerfile: ./JobsApi.AuthedGateway/Dockerfile
          directory: ./JobsApi.AuthedGateway
          tags: latest, v1.0.${{ github.run_number }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

  buildapp-jobscore:
    name: Build JobsApi.JobsCore Docker Image & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & Push JobsApi.JobsCore Docker Image
        with:
          image: ghcr.io/mrkresnofatih/jobsapi-jobscore
          registry: ghcr.io
          dockerfile: ./JobsApi.JobsCore/Dockerfile
          directory: ./JobsApi.JobsCore
          tags: latest, v1.0.${{ github.run_number }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

  buildapp-loggerapp:
    name: Build JobsApi.LoggerApp Docker Image & Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & Push JobsAPI.LoggerApp Docker Image
        with:
          image: ghcr.io/mrkresnofatih/jobsapi-loggerapp
          registry: ghcr.io
          dockerfile: ./JobsAPI.LoggerApp/Dockerfile
          directory: ./JobsAPI.LoggerApp
          tags: latest, v1.0.${{ github.run_number }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}